### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by walidsa3d** [thomacer/zflix#2]
For subtitles support, I suggest you see this : https://github.com/walidsa3d/peersub and this : https://github.com/andy-pham/subflix for inspiration.
Good work.

**Comment by tperale** [comment]
https://github.com/thomacer/zflix/commit/344319554e2b39e5d55c2bae8557bb0a36a18709
Hey, I added the support of opensubtitle subtitle download  (i choosed it because it's where i go most of the time to get mines), but I will probably add peersub support later. It's still a little bit buggy sometime but it worked for the test i ran. Thank you for the feature request and sorry for closing it only now but i had some work to do those last months. :)
